[platformio]
default_envs = pico

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#9c167c6b8aac4f4cfa6d55a0c4e5b848795150c0
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.3
build_flags =
  -D OPENPAW_PRESSURE_PIN=26
  -D OPENPAW_WS2812_PIN=16
  -D OPENPAW_WS2812_COUNT=8
  -D OPENPAW_PRESS_THRESHOLD=1900
  -D OPENPAW_RELEASE_THRESHOLD=1500
  -D OPENPAW_DEBOUNCE_MS=20
